### ISSUE TITLE
Publishing of resources does not work

### ISSUE THREAD

**Issue by klaxa** [FabioGuin/livewire-searchable-select#1]
Hi, first of all cool project, it fills a nice gap!

I'm having trouble extending it though. I cannot seem to publish the view resources. I am using laravel with sail, maybe that makes a difference? I am still quite new to laravel, so maybe it's something obvious that I am missing.

Here is my terminal output:

```
$ ./vendor/bin/sail artisan vendor:publish --provider="FabioGuin\LivewireSearchableSelect\LivewireSelectServiceProvider" --tag="views"

   INFO  No publishable resources for tag [views].  
```

Maybe you can point me in the right direction?

Thanks!

**Comment by FabioGuin** [comment]
Hi klaxa, thank you for the feedback!

There was simply a typo on the service provider namespace in the README file.

I just released the version with the fix, so:
- re-run a `composer update`
- copy the correct command from the README file and run it

:)
