### ISSUE TITLE
Custom callback to generate search results

### ISSUE THREAD

**Issue by klaxa** [FabioGuin/livewire-searchable-select#2]
Hi, this is a suggestion for an improvement to add even more flexibility:

It would be useful to be able to pass a custom callback function that receives the search-term and returns search results. This would enable custom searches over anything and not just a specific model. In my/our case a search function already exists and is used elsewhere and being able to reuse it would be very useful.

Please let me know what you think, I would probably also be able to assist in implementing and/or reviewing!

Thanks!

**Comment by FabioGuin** [comment]
Hi again,
great suggestion! I had thought of something like this for future versions.

I'm keeping this issue open so i'll let you know.

Thank you!

**Comment by FabioGuin** [comment]
Hi! I have add new param: model-app-scope for now, check it out!
