### ISSUE TITLE
Error install laravel 11.14.0

### ISSUE THREAD

**Issue by ozkun-code** [FabioGuin/livewire-searchable-select#3]
I installed Laravel 10.10 and it was fine, but when I installed Laravel 11 an error occurred, or there was a step I missed.
![image](https://github.com/FabioGuin/livewire-searchable-select/assets/51344185/af8a6320-0389-4075-a2ca-75c7d57c8b6a)

**Comment by FabioGuin** [comment]
Hi! Thank you for the report.
I have fix problem in new release, so update your Composer.

Any other suggestion is appreciated :)
